### ISSUE TITLE
ament_uncrustify crash on uncrustify nonzero exit code

### ISSUE THREAD

**Issue by rotu** [ament/ament_lint#227]
Ament uncrustify crashes on certain failure conditions with messy output and the eventual error message `TypeError: 'int' object is not iterable`

This is due to expecting `invoke_uncrustify` to return a list of files, though sometimes it returns an integer return code.

Further, the stack trace is omitted and the error message is duplicated in main.py (so you can't tell which subprocess call failed) and if there is any output from the failed subprocess, it is unclear what that output is.

https://github.com/ament/ament_lint/blob/b8b66ca0bb91fea492b202efa2d761de07569763/ament_uncrustify/ament_uncrustify/main.py#L128-L130

```
The invocation of 'uncrustify' failed with error code 1: Command '['/usr/bin/uncrustify', '-c', '/opt/ros/master/install/lib/python3.8/site-packages/ament_uncrustify/configuration/ament_code_style.cfg', '-l', 'C', '--prefix', '/tmp/uncrustify_559rpet5', '--suffix', '.uncrustify', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/metadata.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/metadata__functions.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/metadata__functions.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/metadata__struct.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/metadata__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/msg/rosidl_generator_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/srv/get_metadata.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/srv/get_metadata__functions.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/srv/get_metadata__functions.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/srv/get_metadata__struct.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_c/ouster_msgs/srv/get_metadata__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_py/ouster_msgs/_ouster_msgs_s.ep.rosidl_typesupport_c.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_py/ouster_msgs/_ouster_msgs_s.ep.rosidl_typesupport_fastrtps_c.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_py/ouster_msgs/_ouster_msgs_s.ep.rosidl_typesupport_introspection_c.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_py/ouster_msgs/msg/_metadata_s.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_generator_py/ouster_msgs/srv/_get_metadata_s.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_c/ouster_msgs/msg/rosidl_typesupport_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_fastrtps_c/ouster_msgs/msg/metadata__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_fastrtps_c/ouster_msgs/msg/rosidl_typesupport_fastrtps_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_fastrtps_c/ouster_msgs/srv/get_metadata__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_fastrtps_cpp/ouster_msgs/msg/rosidl_typesupport_fastrtps_cpp__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_introspection_c/ouster_msgs/msg/metadata__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_introspection_c/ouster_msgs/msg/metadata__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_introspection_c/ouster_msgs/msg/rosidl_typesupport_introspection_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_introspection_c/ouster_msgs/srv/get_metadata__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/ouster_msgs/rosidl_typesupport_introspection_c/ouster_msgs/srv/get_metadata__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_conversions/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/model_coefficients.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/model_coefficients__functions.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/model_coefficients__functions.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/model_coefficients__struct.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/model_coefficients__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/point_indices.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/point_indices__functions.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/point_indices__functions.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/point_indices__struct.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/point_indices__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/polygon_mesh.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/polygon_mesh__functions.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/polygon_mesh__functions.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/polygon_mesh__struct.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/polygon_mesh__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/rosidl_generator_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/vertices.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/vertices__functions.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/vertices__functions.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/vertices__struct.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/msg/vertices__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/srv/update_filename.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/srv/update_filename__functions.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/srv/update_filename__functions.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/srv/update_filename__struct.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_c/pcl_msgs/srv/update_filename__type_support.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/_pcl_msgs_s.ep.rosidl_typesupport_c.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/_pcl_msgs_s.ep.rosidl_typesupport_fastrtps_c.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/_pcl_msgs_s.ep.rosidl_typesupport_introspection_c.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/msg/_model_coefficients_s.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/msg/_point_indices_s.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/msg/_polygon_mesh_s.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/msg/_vertices_s.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_generator_py/pcl_msgs/srv/_update_filename_s.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_c/pcl_msgs/msg/rosidl_typesupport_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/msg/model_coefficients__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/msg/point_indices__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/msg/polygon_mesh__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/msg/rosidl_typesupport_fastrtps_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/msg/vertices__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_c/pcl_msgs/srv/update_filename__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_fastrtps_cpp/pcl_msgs/msg/rosidl_typesupport_fastrtps_cpp__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/model_coefficients__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/model_coefficients__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/point_indices__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/point_indices__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/polygon_mesh__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/polygon_mesh__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/rosidl_typesupport_introspection_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/vertices__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/msg/vertices__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/srv/update_filename__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/build/pcl_msgs/rosidl_typesupport_introspection_c/pcl_msgs/srv/update_filename__type_support.c', '/home/dan/Documents/ros_ouster_ws/build/perception_pcl/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c', '/home/dan/Documents/ros_ouster_ws/build/ros2_ouster/CMakeFiles/3.16.3/CompilerIdC/CMakeCCompilerId.c', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/metadata__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/rosidl_generator_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/rosidl_typesupport_fastrtps_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/rosidl_typesupport_fastrtps_cpp__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/msg/rosidl_typesupport_introspection_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/ouster_msgs/srv/get_metadata__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_conversions/pcl_conversions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/model_coefficients__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/point_indices__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/polygon_mesh__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/rosidl_generator_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/rosidl_typesupport_fastrtps_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/rosidl_typesupport_fastrtps_cpp__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/rosidl_typesupport_introspection_c__visibility_control.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/msg/vertices__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__functions.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__functions.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__rosidl_typesupport_fastrtps_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__rosidl_typesupport_introspection_c.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__struct.h', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__type_support.c', '/home/dan/Documents/ros_ouster_ws/install/include/pcl_msgs/srv/update_filename__type_support.h', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/ouster_msgs/msg/_metadata_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/ouster_msgs/srv/_get_metadata_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/pcl_msgs/msg/_model_coefficients_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/pcl_msgs/msg/_point_indices_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/pcl_msgs/msg/_polygon_mesh_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/pcl_msgs/msg/_vertices_s.c', '/home/dan/Documents/ros_ouster_ws/install/lib/python3.8/site-packages/pcl_msgs/srv/_update_filename_s.c', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_conversions/include/pcl_conversions/pcl_conversions.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/pcl_nodelet.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/point_cloud.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/publisher.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/transforms.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/boundary.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/feature.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/fpfh.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/fpfh_omp.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/moment_invariants.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/normal_3d.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/normal_3d_omp.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/normal_3d_tbb.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/pfh.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/principal_curvatures.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/shot.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/shot_omp.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/features/vfh.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/crop_box.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/extract_indices.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/filter.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/passthrough.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/project_inliers.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/radius_outlier_removal.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/statistical_outlier_removal.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/filters/voxel_grid.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/io/bag_io.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/io/concatenate_data.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/io/concatenate_fields.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/io/pcd_io.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/segmentation/extract_clusters.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/segmentation/extract_polygonal_prism_data.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/segmentation/sac_segmentation.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/segmentation/segment_differences.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/surface/convex_hull.h', '/home/dan/Documents/ros_ouster_ws/src/perception_pcl/pcl_ros/include/pcl_ros/surface/moving_least_squares.h']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/ros/master/install/bin/ament_uncrustify", line 11, in <module>
    load_entry_point('ament-uncrustify==0.8.1', 'console_scripts', 'ament_uncrustify')()
  File "/opt/ros/master/install/lib/python3.8/site-packages/ament_uncrustify/main.py", line 130, in main
    all_output_files += output_files
TypeError: 'int' object is not iterable
```

**Comment by dirk-thomas** [comment]
This is a regression of #214.
