### ISSUE TITLE
pycodestyle failure in flake8

### ISSUE THREAD

**Issue by tfoote** [ament/ament_lint#279]
The linux packaging job is failing due to what appears to be a flake8 API change

https://ci.ros2.org/view/packaging/job/packaging_linux/lastCompletedBuild/consoleText

`AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'`

<details>

```
4: Test command: /home/jenkins-agent/workspace/packaging_linux/venv/bin/python3 "-u" "/home/jenkins-agent/workspace/packaging_linux/ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml" "--package-name" "ros1_bridge" "--output-file" "/home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/ament_flake8/flake8.txt" "--command" "/home/jenkins-agent/workspace/packaging_linux/ws/install/bin/ament_flake8" "--xunit-file" "/home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml"
4: Test timeout computed to be: 60
4: -- run_test.py: invoking following command in '/home/jenkins-agent/workspace/packaging_linux/ws/src/ros2/ros1_bridge':
4:  - /home/jenkins-agent/workspace/packaging_linux/ws/install/bin/ament_flake8 --xunit-file /home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml
4: Traceback (most recent call last):
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 157, in load_plugin
4:     self._load()
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 134, in _load
4:     self._plugin = self.entry_point.load()
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 98, in load
4:     return functools.reduce(getattr, attrs, module)
4: AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'
4: 
4: During handling of the above exception, another exception occurred:
4: 
4: Traceback (most recent call last):
4:   File "/home/jenkins-agent/workspace/packaging_linux/ws/install/bin/ament_flake8", line 33, in <module>
4:     sys.exit(load_entry_point('ament-flake8==0.8.2', 'console_scripts', 'ament_flake8')())
4:   File "/home/jenkins-agent/workspace/packaging_linux/ws/install/lib/python3.6/site-packages/ament_flake8/main.py", line 75, in main
4:     max_line_length=args.linelength)
4:   File "/home/jenkins-agent/workspace/packaging_linux/ws/install/lib/python3.6/site-packages/ament_flake8/main.py", line 176, in generate_flake8_report
4:     style = get_flake8_style_guide(flake8_argv)
4:   File "/home/jenkins-agent/workspace/packaging_linux/ws/install/lib/python3.6/site-packages/ament_flake8/main.py", line 140, in get_flake8_style_guide
4:     application.find_plugins(config_finder)
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/main/application.py", line 159, in find_plugins
4:     self.check_plugins.load_plugins()
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 415, in load_plugins
4:     plugins = list(self.manager.map(load_plugin))
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 302, in map
4:     yield func(self.plugins[name], *args, **kwargs)
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 413, in load_plugin
4:     return plugin.load_plugin()
4:   File "/home/jenkins-agent/workspace/packaging_linux/venv/lib/python3.6/site-packages/flake8/plugins/manager.py", line 164, in load_plugin
4:     raise failed_to_load
4: flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
4: -- run_test.py: return code 1
4: -- run_test.py: generate result file '/home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml' with failed test
4: -- run_test.py: verify result file '/home/jenkins-agent/workspace/packaging_linux/ws/build/ros1_bridge/test_results/ros1_bridge/flake8.xunit.xml'
1/1 Test #4: flake8 ...........................***Failed    0.43 sec
```
</details>

This appears to be a flakey test with the same failure 8 builds ago.
* https://ci.ros2.org/view/packaging/job/packaging_linux/2117
* https://ci.ros2.org/view/packaging/job/packaging_linux/2125

**Comment by tylerjw** [comment]
As explained here: https://gitlab.com/pycqa/flake8/-/issues/406

it looks like the maintainer of pycodestyle removed the symbol break_around_binary_operator.

Here is the fix they landed on for this issue: https://gitlab.com/pycqa/flake8/-/merge_requests/230/diffs

I'll try to make a similar change and submit it as a PR.

**Comment by clalancette** [comment]
This looks like it isn't happening anymore, so I'm going to go ahead and close this issue out.  Feel free to reopen if I closed it in error.
