### ISSUE TITLE
Support clang format file with multiple languages

### ISSUE THREAD

**Issue by max-os-lg** [ament/ament_lint#364]
Right now we have a clang format file with multiple configurations for different languages.  
With a call to `clang-format` this is working but not with `ament_clang_format`.  

Example:  

```
Language: Cpp
BasedOnStyle: Google
---
Language: Proto
BasedOnStyle: Google
```

Error:  

```
Traceback (most recent call last):
  File "/opt/ros/galactic/bin/ament_clang_format", line 11, in <module>
    load_entry_point('ament-clang-format==0.10.6', 'console_scripts', 'ament_clang_format')()
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_clang_format/main.py", line 101, in main
    data = yaml.safe_load(content)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    Language: Cpp
    ^
but found another document
  in "<unicode string>", line 55, column 1:
    ---
    ^

```

**Comment by aprotyas** [comment]
This is difficult because it looks like there are two challenges here:
1. `ament_clang_format`'s workaround to having a configuration file at the `clang-format` calling directory is to load the configuration file (YAML) and dump its contents as the `-style` flag at runtime.
The YAML error above comes from `yaml.load/dump` of the provided config file. Each `---` delimited section corresponds to a new document in a YAML file, and the `load/dump` interface expects only one document to be passed to it. It can be resolved with `yaml.load_all/dump_all`, but even then `ament_clang_format` can't really combine two YAML documents into one output stream to pass to the `-style` flag.
Again, this problem exists because `ament_clang_format` is trying to work around the fact that till [clang-format 14.0.0](https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#clang-format), configuration files could not be placed in arbitrary directories.
If you're working with a new enough version of `clang-format`, I reckon the following patch to `ament_clang_format` will suffice:
```diff
-    with open(args.config_file, 'r') as h:
-        content = h.read()
-    data = yaml.safe_load(content)
-    style = yaml.dump(data, default_flow_style=True, width=float('inf'))
     cmd = [clang_format_bin,
            '-output-replacements-xml',
-           '-style=%s' % style]
+           '-style=file:%s' % args.config_file]
```

2. `clang-format` also requires explicitly passing to it the files that we would like to lint. `ament_clang_format` works around it with a known list of extensions to match against when traversing through a package. Right now, `proto` files are not part of that list of extensions, but this is just a matter of adding `proto` to the list of accepted extensions.

---

Having said all this, I think my suggestion would be to either use a fork of `ament_clang_format` that fits your needs - i.e. `proto` file extension and directly passing a config file (if you have access to a `clang-format`>=14.0.0 binary), or to do linting directly with `clang-format`.
