### ISSUE TITLE
ament_flake8 fails with flake8>=5.0.0

### ISSUE THREAD

**Issue by christophebedard** [ament/ament_lint#399]
```
build/test_tracetools/test_results/test_tracetools/flake8.xunit.xml: 1 test, 1 error, 0 failures, 0 skipped
- test_tracetools flake8.xunit.missing_result
  <<< error message
    The test did not generate a result file:
    
    Traceback (most recent call last):
      File "/root/ws/install/ament_flake8/bin/ament_flake8", line 33, in <module>
        sys.exit(load_entry_point('ament-flake8', 'console_scripts', 'ament_flake8')())
      File "/root/ws/build/ament_flake8/ament_flake8/main.py", line 30, in main
        rc, _ = main_with_errors(argv=argv)
      File "/root/ws/build/ament_flake8/ament_flake8/main.py", line 87, in main_with_errors
        report = generate_flake8_report(
      File "/root/ws/build/ament_flake8/ament_flake8/main.py", line 186, in generate_flake8_report
        style = get_flake8_style_guide(flake8_argv)
      File "/root/ws/build/ament_flake8/ament_flake8/main.py", line 150, in get_flake8_style_guide
        config_finder = config.ConfigFileFinder(
    AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
  >>>
```

It seems like `flake8.options.config.ConfigFileFinder` was removed in 5.0.0.

```sh
$ pip3 list -v | grep flake8
flake8                        5.0.0                                             /home/chris/.local/lib/python3.8/site-packages pip
$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flake8.options.config import ConfigFileFinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (/home/chris/.local/lib/python3.8/site-packages/flake8/options/config.py)
>>>
$ pip3 install 'flake8<5.0.0'
...
$ pip3 list -v | grep flake8
flake8                        4.0.1                                             /home/chris/.local/lib/python3.8/site-packages pip
$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flake8.options.config import ConfigFileFinder
>>> 
```

It's used here:

https://github.com/ament/ament_lint/blob/96d9ca4fd32b18a1e083b9e952930c93251be4f4/ament_flake8/ament_flake8/main.py#L150-L151

**Comment by clalancette** [comment]
Yeah.  I think in the short-term, I'm going to end up pinning flake8 in CI to the appropriate version; that's what our users will be seeing.  Longer term, we'll have to address this.

**Comment by mikepurvis** [comment]
Addressed by https://github.com/ament/ament_lint/pull/410, it seems.
